kind: pipeline
name: manifest

platform:
  os: linux

steps:
- image: plugins/manifest
  settings:
    username: rkojedzinszky
    password:
      from_secret: hub_docker_password
    auto_tag: true

depends_on: []
